### ISSUE TITLE
Touring Sidebar

### ISSUE THREAD

**Issue by keckelt** [datavisyn/tdp_core#122]
Create a touring side bar in Ordino that:

-  has a button in [LineUpPanelActions](https://github.com/datavisyn/tdp_core/blob/master/src/lineup/internal/LineUpPanelActions.ts): 
![image](https://user-images.githubusercontent.com/10337788/44707300-6cb59c80-aaa4-11e8-86c0-4fe8aa2a7c7c.png)
 - overlays / replaces the side bar with the touring view

---
Subtasks:

 * [x] Add touring panel and button to open it
 * [x] Add selector for items / attributes
 * [x] Add similarity measure manager to select measures based on types: <ISSUE>
 * [ ] Add config for manager to define/weight prefered similarity measures for a given type comparison
 * [ ] Add similarity measure tests
 * [x] Add similarity measures
 * [ ] Add manager tests
 * [x] Add table to display scores

⛵ At this point, the touring is usable

---

 * [x] Let users select Table input (what to compare with what) 
 * [x] Color code table like heatmap
 * [ ] Config for significance theshold (significant / not significant)

⛵ The table looks nice and should fit the space

---

Add mini visualizations to describe scores:
* [ ] Add visualization manager to select visualization based on measure / type
* [ ] Add config for manager to define/weight prefered visualization for a given type comparison
* [ ] Add manager tests
* [ ] Add visualizations tests
* [ ] Add visualizations
* [ ] Display visualizations on click/hover

⛵ done

**Comment by keckelt** [comment]
Point users to the new feature: #131

**Comment by keckelt** [comment]
In addition to visualizing the similarity score, we could also plot the density function used to determine the p-value

**Comment by mstreit** [comment]
yes. this should be discussed with thomas.

**Comment by mstreit** [comment]
@keckelt and @PatrickAdelberger, can you please extract the missing/unfinished touring features/TODOs to separate issues? this way it's easier to track the progress - also for BI.

**Comment by keckelt** [comment]
Moved to https://github.com/Caleydo/tdp_bi_bioinfodb/issues/903.
