### ISSUE TITLE
Touring Sidebar - BI Feedback (16.10.18)

### ISSUE THREAD

**Issue by PatrickAdelberger** [datavisyn/tdp_core#129]
Usually **20.000** genes are the maximum number of items, but the touring should work for at least **2.000** items.

SG...   **S**tratification **G**roups
DD...   **D**rop**D**own 

### Discussion
- [ ] 10+ columns behaviour
- [ ] collapse all attributes in table --> a second DD is not needed
- [ ] alternative input selection
  - use 1 DD + collapsable table rows
  - use 2 DD
    - @PatrickAdelberger draft (2 DD)
- [ ] use histogram/violin plot instead of boxplot: https://github.com/Caleydo/tdp_bi_bioinfodb/issues/908
- [ ] if table too big --> create a list of most significant and switch to this one on deman: https://github.com/Caleydo/tdp_bi_bioinfodb/issues/907
- [x] one table to rule them all
  - [x] symbols for the attributes to indicate the type (categorical, numerical)
  - [x] show only p-values in table and more information (type of score, ...) in the mini visualisation
- [ ] default setting: compare 1 to all: https://github.com/Caleydo/tdp_bi_bioinfodb/issues/906
  - indicates the link to the input elements
  - faster score calculations ( than all against all)
- [x] remove duplicate entries in table (below of above diagonal)

#### General
- [x] change tab labels:  **Items** --> **Rows** and **Attributes** --> **Columns**
- [x] increase touring sidebar width 
- [x] fix error with genes / cell lines for stratification
  - order and row id do not match
- [x] adjusted Rank index for numerical
- [x] improve calculation time for items tab (like attributes tab) ( #130 )
- [ ] right margin/padding changes when vertical scroll bar is displayed: https://github.com/Caleydo/tdp_bi_bioinfodb/issues/909
- [x] adjusted Rank does not update after stratification is changed
- [x] ~~multiple boxplots are highlighted if next selection is in the same row~~
 
#### Table & Scores
- [x] adjust text colour: depending on background
- [x] rename **Mann-Whitney-U Test** to **Wilcoxon Rank-Sum Test**
- [x] selected cell in table should stay highlighted
- [x] use always the significance --> **p-value**
- [ ] horizontal scroll bar is not visible for long tables: https://github.com/Caleydo/tdp_bi_bioinfodb/issues/909 
- [ ] **Selection** is not needed for comparison SG with SG
- [x] Jaccard: p-value instead of jaccard score (fisher exact test)
- [x] only meaningful test:
  - [x] no t-test for categorical columns
  - [x] no jaccard score for numerical columns

#### Simplification
- [ ] for too many columns only the most significant ones should be shown, see https://github.com/Caleydo/tdp_bi_bioinfodb/issues/907
- [ ] collapsable attributes and show only most significant group, 
- [x] better description for the different selections for the use cases
  - SG with category: overlap of groups with categorical values
  - SG with SG: pairwise group comparison
  - selection with ...

#### Mini Visualisation ( #132 )
- [ ] Visualisation Details
  - [x] display score & p-value
  - [ ] what is compared
  - [ ] what is the information this score gives
- [x] Parallel Sets 
  - [x] move label of 2nd dimension underneath the plot
  - [x] adjust label for small categories (currently not readable)
  - [x] only display the selected column and row
    - [x] change the 2 dimensions: 1 =[selectedRow + others] & 2 = [selectedColumn + others]
    - [x] change sizes of the used sets to the union of the 2 selected sets
  - [x] change vis for the comparison of SG with SG 
- [x] Box Plot
  - [x] color of box plots should be the color of the column and higher opacity for the selected one

**Comment by keckelt** [comment]
All actions are done or moved to separate issues (linked directly in the list)
