### ISSUE TITLE
Extract Touring/TourDino from tdp_core to a separate repo

### ISSUE THREAD

**Issue by thinkh** [datavisyn/tdp_core#257]
The goal of this issue should be the integration of Touring/TourDino into tdp_core.

TourDino adds an additionall button to the `ARankingView` which opens a new panel. The user can statistically evaluate the selections/groups of rows and columns. See also the [video and publication](http://caleydo.org/publications/2019_eurova_tourdino/). 

![grafik](https://user-images.githubusercontent.com/5851088/69532315-d194c680-0f75-11ea-8c8c-71442ed07d5d.png)

Demo: https://tourdino.caleydoapp.org/

The current implementation consists of two parts:

1. [Klaus' touring branch @ tdp_core](https://github.com/datavisyn/tdp_core/compare/develop...keckelt/122/touring?expand=1)
2. [tourdino repo](https://github.com/Caleydo/tourdino)

**Tasks**

- [ ] Create a new `touring` branch
- [ ] Copy directory and files from Klaus' branch to the new touring branch
- [ ] Rename directories to lower case (e.g., `src/lineup/internal/Touring/Tasks` -> `src/lineup/internal/touring/tasks`)
- [x] Try to revert to `es5` as compiler target in _tsconfig.json_ (see https://github.com/datavisyn/tdp_core/compare/develop...keckelt/122/touring?expand=1#diff-e5e546dd2eb0351f813d63d1b39dbc48R4)
- [x] Related to ES5: Enable uglifyjs in Webpack config again (see https://github.com/datavisyn/tdp_core/compare/develop...keckelt/122/touring?expand=1#diff-11e9f7f953edc64ba14b0cc350ae7b9dL354-L424)
- [ ] [TourDino code](https://github.com/Caleydo/tourdino) is integrated in tdp_core 
   * i.e., no dependency to the tourdino repository in _package.json_
   * should be placed under `tdp_core/src/lineup/internal/touring/` 
- [ ] Move classes `ATouringTask`, `RowComparison`, and `ColumnComparison` to separate files
- [ ] Separate and move Cypress dependencies, config and tests (for Ordino) to [Caleydo/ordino](https://github.com/Caleydo/ordino)
- [ ] The Touring button in ARankingView should be configurable (i.e., a show/hide via config flag)
- [ ] Check if we can add the `TouringPanel` as additional button to  `LineUpPanelActions` instead of extending it (https://github.com/datavisyn/tdp_core/compare/develop...keckelt/122/touring?expand=1#diff-cc189df66218eaa3efd10d242eecc43bR7 and https://github.com/datavisyn/tdp_core/compare/develop...keckelt/122/touring?expand=1#diff-1b221b616102ce7d3e8e458b2fbfde44R296)

**Definition of Done**

- [ ] The new panel must open
- [ ] All statistical measurements must work

**Comment by keckelt** [comment]
I think newer versions of ebpack / its Uglify plugin support es6. Maybe you can use it after switching to TS v3.
Or do you stick with es5?

**Comment by thinkh** [comment]
@keckelt We will use ES5 as compile target as long we are using TypeScript 2. We found a way in the tourdino repository to down-compile the ES6 features. See https://github.com/Caleydo/tourdino/pull/9

**Comment by thinkh** [comment]
In a personal meeting with @lehnerchristian, @dg-datavisyn and @oltionchampari we decided to extract the touring integration from tdp_core to the separate [tourdino repository](https://github.com/Caleydo/tourdino/). We will provide extensions points in tdp_core to be used by tourdino.
